### ISSUE TITLE
[ 0.5pt ] Kanban Board Project Setup

### ISSUE THREAD

**Issue by 41hulk** [41hulk/capstone-javascript#4]
- [ ] Kanban Project setup.

### Project by
- Ntare Guy
- Fernando Silva

Link: https://github.com/41hulk/capstone-javascript/projects/1

**Comment by Amrhub** [comment]
Hi Team,  👋🏻 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!
These changes aim to add some awesomeness to your awesome project and code skills.

## Required Changes ♻️
_Check the comments under the review._
![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

- [ ] We are supposed to have 15 cards since we are a group of two collaborators, Let's make sure we follow [these steps](https://github.com/microverseinc/curriculum-tools-copy-projects) correctly and it should set up the cards for us and make sure that each task has assignee

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rustam-tolipov** [comment]
## Hello team👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉, 

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by fernando-silvabr66** [comment]
Thanks for the review!!!
